spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ohriniuc.eduard2@gmail.com
    password: vbdwkqtodiymqbzw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
             enable: true